### PR TITLE
Add GUI with toga/briefcase

### PR DESCRIPTION
**Pull request by sinedie**
GUI make on Toga made to be packaged with Briefcase. It works for deepl-scrap but still is a work in progress.

The ideal is to release packages for all mayor systems (windows, linux, mac).

It is an initial aproach, not production ready.

### CODE REVIEW

**Comment by k-aito** [comment]
Hello @sinedie 

You were faster than me, I would interest in understanding your code later if you don't mind.
I still have no time for now but later because I had some issues with the terminal think, async and other stuff. If I can learn a bit more, I'm interested ^^

Good luck for the rest of it.

**Comment by k-aito** [comment]
Hello again @sinedie 
 I noticed you don't have the GitHub action for the building, I think you can reuse the one I tried to use https://github.com/k-aito/SRTranslator/blob/convert-to-briefcase/.github/workflows/briefcase_build_docker.yml

I didn't add the macOS part because I have read that it must be signed now, so it was not really useful, but maybe there are other people that could confirm that or help us.

I read the code and I didn't notice the children parameter, it makes the code so much easier to read. And the loop that I never used, I guess my biggest issues was from there. I'm well a little curious about the xprint and terminal how found them? I don't remember having read anything like that.

**Comment by sinedie** [comment]
Ty for sharing this config, i'll take a look to it when I have any spare time.

Children parameter is cool, but I would like to implement an XML parser to declare layout from a outside-code file. That way is even more flexible but thats a Toga related issue (they want it and I want to try doing it).

The loop with asyncio is kind of necessary but we should disable buttons while translating, I think is a little confusing right now cause there is not visual hint that transaltion is processing.

I overloaded print builtin function cause didnt want to make a progress bar -also was a little complicated to extract the progress variables without changing the CLI tool and again, the idea is to keep it as it is and dont mess that code-. I just google "overload builtin print python" (or something similar, I dont remember) searching a way to put the print statements on toga screen

Also, I'll do it when i have time, but if you want to help, we need a configuration form to save API keys and wrap limits. The idea is to make it a dialog triggered by a command in the toolbar.

**Comment by k-aito** [comment]
Hello @sinedie 

I cannot promise when, but if I have time I will, I will also close my branch because there is no real goal to try doing weird stuff when you have something working and with a readable code ^^

**Pull request merged**
